PERMISO_LEER = 'r'
PERMISO_ESCRIBIR = 'bw'
TAMANO_NORM = 2
STD_SIZE = 2
COMP_2_BYTES = "0"
MIN_BYTES_VER = 10
MAX_REINICIO = 5
CAMINO_FIFO_AGENTE = "fifoPipeAgente"
CAMINO_FIFO_NODO = "fifoPipeNodo"
ERR_PIPE_BORRAR_L = "No se eliminó pipe de lectura"
ERR_PIPE_BORRAR_E = "No se eliminó pipe de escritura"
ERR_PIPE_ABRIR_L = "No se abrió el pipe de lectura"
ERR_PIPE_ABRIR_E = "No se abrió el pipe de escritura"
ERR_PIPE_CERRAR_L = "No se cerró pipe de lectura"
ERR_PIPE_CERRAR_E = "No se cerró pipe de escritura"
ERR_REC_CONFIRMACION = "No se recibió confimación"
CONF_SIZE  = 3
CODIGO_CONFIRMACION = "777"
ERR_ENV_CONFIRMACION = "No se envió confimación"
PREENVIO_PID = "100"
DIFF_PREENVIO_PID = "El código de preenvío del pid es incorrecto"
CODIGO_FINALIZACION_PID = "101"
CODIGO_AVISO_ENV_VER = "102"
DIFF_AVISO_ENV_VER = "El aviso de recibo de info ver es incorrecto"
DIFF_AVISO_ENV_VEC = "El aviso de recibo de vecinos es incorrecto"
CODIGO_AVISO_REC_VER = "103"
CODIGO_AVISO_ENV_VEC = "104"
CODIGO_AVISO_REC_VEC = "106"
